<?php
module_load_include('inc','simcore','simcore.helper');
global $TU_QUY, $NGU_QUY, $LUC_QUY, $LOC_PHAT, $THAN_TAI, $OND_DIA, $TIEN_DON, $TIEN_DOI;

function simcore_block_info() {
    $blocks = array();

    $blocks['search_sim'] = array(
        'info' => t('Search sim block'),
    );
    return $blocks;
}

function simcore_block_view($delta='') {
    $block = array();
    switch($delta) {
        case 'search_sim' :
            $block['subject'] = t("Công cụ tìm kiếm");
            $block['content'] = simcore_search_block_content();
        break;
    }

    return $block;
}

function simcore_search_block_content() {
    $result_html = theme('block_search_sim');
    return $result_html;
}


function simcore_theme(){
    return array(
    'block_search_sim' =>  array(
    'template' => 'template/search',
    'render element' => 'element'
    )
    );
}

function simcore_node_presave($node){
    if($node->type == 'sim'){
       $result =  _get_kind_of_phone_number($node->title);
       $node->field_lo_i_sim[$node->language][0]['tid'] = $result;
    }
}
